### ISSUE TITLE
Hey, noticed you had some private stuff in public.

### ISSUE THREAD

**Issue by ipavlovski** [Bfgeshka/binfiles#1]
stolen/RutrackerDownloader.sh

**Comment by ipavlovski** [comment]
I saw your awesome config here: https://www.reddit.com/r/unixporn/comments/4az73m/dwm_no_more_conky_for_cli/ 
Tried to find the source, and was going through some of your code. And for the rutracker website you have your authentication in plain text, just thought i would let you know.
Couldn't find a way to send you a DM, so making an issue instead.

Cheers

**Comment by Bfgeshka** [comment]
Wow, i totally forgot about content of this scripts, thanks. I've changed my password already.

I'll update my dotfiles somewhat later btw, right now I'm trying to write a proper gtk theme but failing miserably.
